//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Receipts_dbEntities1 : DbContext
    {
        public Receipts_dbEntities1()
            : base("name=Receipts_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_tbl> Category_tbl { get; set; }
        public virtual DbSet<NumCompeny_tbl> NumCompeny_tbl { get; set; }
        public virtual DbSet<NumCompenyCategory_tbl> NumCompenyCategory_tbl { get; set; }
        public virtual DbSet<Products_tbl> Products_tbl { get; set; }
        public virtual DbSet<Receipt_tbl> Receipt_tbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UnusingWord_tbl> UnusingWord_tbl { get; set; }
        public virtual DbSet<User_tbl> User_tbl { get; set; }
        public virtual DbSet<WordCategory_tbl> WordCategory_tbl { get; set; }
        public virtual DbSet<WordPerCategory> WordPerCategory { get; set; }
        public virtual DbSet<WordPerCategory_tbl> WordPerCategory_tbl { get; set; }
    }
}
