//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_tbl
    {
        public int Id { get; set; }
        public string nameProduct { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<decimal> sumProduct { get; set; }
        public Nullable<int> receipt { get; set; }
    
        public virtual Receipt_tbl Receipt_tbl { get; set; }
        public virtual Receipt_tbl Receipt_tbl1 { get; set; }
    }
}
