//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt_tbl()
        {
            this.Products_tbl = new HashSet<Products_tbl>();
            this.Products_tbl1 = new HashSet<Products_tbl>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> dateReceipt { get; set; }
        public string nameShop { get; set; }
        public string numCompany { get; set; }
        public Nullable<decimal> totalSum { get; set; }
        public string myUser { get; set; }
        public Nullable<int> category { get; set; }
        public string path { get; set; }
    
        public virtual Category_tbl Category_tbl { get; set; }
        public virtual Category_tbl Category_tbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_tbl> Products_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_tbl> Products_tbl1 { get; set; }
        public virtual User_tbl User_tbl { get; set; }
        public virtual User_tbl User_tbl1 { get; set; }
    }
}
